### ISSUE TITLE
Missing permanent token and mismatch between examples and schemas in API reference docs

### ISSUE THREAD

**Issue by marco-sacchi** [fattureincloud/fattureincloud-php-sdk#101]
**Describe the bug**
The `permanent_token` field is present in the responses examples for creation, retrieval and modification of issued documents, but it is not present in the related docs schemes and SDK.

Previously (API v1), the id of the issued documents changes at each modification of the data requiring the use of the permanent token.

Now (API v2) the permanent token is no longer accessible, and even if the `id` remains the same, it makes it impossible to transition from API v1 to v2 without creating disruption to our customers.

**Env info**
Please, provide us with the following details:
- PHP 7.3.32
- PHP SDK 2.0.16

**To Reproduce**
Not applicable.

**Expected behavior**
The documentation should be aligned and the `permanent_token` should be accessible from the SDK, otherwise it becomes impossible to transition to v2 for non-finalized documents, or for documents for which a subsequent modification is made through the API.

I understand it's a major version transition, but I don't think you've overlooked that, so let me know if I've missed anything.

**Comment by emajo** [comment]
Hi @marco-sacchi, to transition from the `permanent_token` to the `id` of the document is not very hard, in [this discussion](https://github.com/fattureincloud/api/discussions/63) we already talked about it. 

Essentially you need to retrieve the id of the document filtering by `number + numeration` and modify your integration to use the id instead of the token.

Let me know if you encounter some kind of problem doing it.
Thanks,
Emanuele.

**Comment by marco-sacchi** [comment]
Hi @emajo, 
I hadn't thought of looking into the discussions too, thanks for the tip.

In any case, if you can please align the API reference, examples vs schemes.

You can close this issue.
Thank you.
