### ISSUE TITLE
Return 500 on createClient

### ISSUE THREAD

**Issue by Mattia-Marchiorato** [fattureincloud/fattureincloud-php-sdk#103]
**Describe the bug**
return a 500 on [entities/clients](https://api-v2.fattureincloud.it/c/companyid/entities/clients) 
{"error":{"message":"An unexpected error occurred. Contact support for more information."}}
**Env info**
Please, provide us with the following details:
- PHP version 8.1
- PHP SDK version 2.0.16

**Expected behavior**
Create a client on FIC or return an error not a 500

**Comment by valmoz** [comment]
Hi @Mattia-Marchiorato 
please contact our customer support. With so limited data we cannot investigate your issue.

Thanks
Mauro

**Comment by Mattia-Marchiorato** [comment]
You have to investigate your 500 error that is not a valid response for an api service.

**Comment by valmoz** [comment]
Hi @Mattia-Marchiorato 
as you correctly said, this is an issue on our API, but:

1. this is the repo of the PHP SDK, and this is not an issue on the SDK but on the API
2. I asked you to contact our support because I needed more detail (e.g. your company id) to detect the issue. 

Luckily I was able to find your company id and the log of your request, the problem seems related to the fact that your request contains the data.ei_code field explicitly set with null value.
`"ei_code": null`

Of course, this is the wrong response for this kind of issue, so we'll deal with it.

**Comment by Mattia-Marchiorato** [comment]
@valmoz you are right, i also opened a chat with support.
In your sdk repo in the https://github.com/fattureincloud/fattureincloud-php-sdk/blob/master/lib/Model/Entity.php
in the  setEiCode method @param annotation we can see null as valid parameter, maybe you have to also fix this.

Thanks for now

MM
